version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: project_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./docker/db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: project_backend
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    networks:
      - app-network
  
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: project_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app-network
  
  nginx:
    image: nginx:alpine
    container_name: project_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge